import Head from "next/head";
import React from "react";
import Header from "../header/Header";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="">
      <Head>
        <title>Next.js + TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className=" min-h-screen overflow-x-hidden container mx-auto p-10">
        {children}
      </main>
    </div>
  );
}
